---

- name: Create and configure ansible-firefox
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: "{{ lookup('env', 'ROLE_NAME') }}"
      tasks_from: main
      state: present

...
